#!/bin/bash
#Testing whether the user is in the system or not
#or whether the particular user has directories left in the system or not
#
clear
echo "Enter the user name: "
read testuser
#
if grep $testuser /etc/passwd
then
   echo "The user $testuser exists on this system."
#
elif ls -d /home/$testuser
then
   echo "The user $testuser does not exists on this system."
   echo "However, $testuser has a directory."
#
else
   echo "The user $testuser does not esist on this system."
   echo "And, $testuser does not have a directory."
fi
