#!/bin/bash
#Testing whether the user is in the system or not

clear
#
echo "Enter the username"
read testuser
if grep $testuser /etc/passwd
then
   echo "The bash files for $testuser are:"
   ls -a /home/$testuser
   echo ""
else
   echo "The user $testuser does not exist on this system."
   echo ""
fi 
